//
//  SkyGoldenTests.swift
//  PopcornEPG
//
//  Copyright © 2026 Adam Young.
//

import Foundation
@testable import PopcornEPG
import Testing

struct SkyGoldenTests {

    private static let date = "20261006"
    private static let london = RegionRef(bouquet: 4101, subBouquet: 1)

    /// The batch fixture's SIDs, in response order, that also appear in the services fixture.
    /// Only 14 of its 20 SIDs are in the 4101/1 line-up, so the golden output covers those 14.
    private static func goldenChannels() throws -> [Channel] {
        let batch = try Fixtures.decode(SkyScheduleResponse.self, from: Fixtures.scheduleBatch)
        let services = try Fixtures.decode(SkyServicesResponse.self, from: Fixtures.services)
        let channelsBySID = Dictionary(
            EPGService(apiClient: stub()).buildChannels(from: services.services.map { ($0, london) })
                .map { ($0.sid, $0) }
        ) { first, _ in first }

        return (batch.schedule ?? []).compactMap { channelsBySID[$0.sid] }
    }

    /// Answers multi-SID requests with the batch fixture and SID 1003 with its single-SID fixture.
    private static func stub() -> SkyAPIStub {
        SkyAPIStub { request in
            if request.sids.count > 1 {
                return try Fixtures.decode(SkyScheduleResponse.self, from: Fixtures.scheduleBatch)
            }
            if request.sids == ["1003"] {
                return try Fixtures.decode(SkyScheduleResponse.self, from: Fixtures.scheduleSID1003)
            }
            throw SkyAPIStub.StubError.notStubbed
        }
    }

    private static func encodedProgrammes(of channel: Channel?) throws -> Data {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys]
        return try encoder.encode(channel?.schedules.first?.programmes ?? [])
    }

    @Test
    func goldenChannelsCoverTheFourteenSIDsInBothFixtures() throws {
        let sids = try Self.goldenChannels().map(\.sid)

        #expect(sids == [
            "1003", "1005", "1009", "1011", "1015", "1016", "1018",
            "1019", "1023", "1026", "1030", "1036", "1041", "1042"
        ])
    }

    /// Pins current behaviour: `expected-schedule-20261006.json` was generated by running this pipeline once
    /// against the captured fixtures. Regenerate it only when an output change is intended.
    @Test
    func batchedFetchWritesExpectedScheduleFile() async throws {
        let stub = Self.stub()
        let channels = try Self.goldenChannels()
        let epg = await EPGService(apiClient: stub).fetchSchedules(for: channels, dates: [Self.date])
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("SkyGoldenTests-\(UUID().uuidString)", isDirectory: true)
        defer { try? FileManager.default.removeItem(at: directory) }

        try SiteWriter(directory: directory).write(epg)

        let written = try Data(contentsOf: directory.appendingPathComponent("schedules/\(Self.date).json"))
        #expect(stub.scheduleRequests.count == 1)
        #expect(try written == (Fixtures.data("expected-schedule-20261006.json")))
    }

    @Test
    func singleSIDFetchMatchesBatchedFetchForSID1003() async throws {
        let channels = try Self.goldenChannels()
        let channel = try #require(channels.first { $0.sid == "1003" })

        let batched = await EPGService(apiClient: Self.stub()).fetchSchedules(for: channels, dates: [Self.date])
        let single = await EPGService(apiClient: Self.stub()).fetchSchedules(for: [channel], dates: [Self.date])

        let batchedProgrammes = try Self.encodedProgrammes(of: batched.channels.first { $0.sid == "1003" })
        #expect(single.channels.first?.schedules.first?.programmes.count == 36)
        #expect(try Self.encodedProgrammes(of: single.channels.first) == batchedProgrammes)
    }

}
